### ISSUE TITLE
Crash when loading python script while LCM is playing

### ISSUE THREAD

**Issue by patmarion** [openhumanoids/signal-scope#6]
This is not an issue when you load a python script at startup.  It is an issue if you load a new script at runtime via File --> Open Python Script.

To avoid the crash, the LCM thread needs to be paused while loading the script.  LCM handlers are fired on a separate thread, so the problem is that the main thread is loading the python script while the LCM handlers are decoding messages in Python, this crashes the Python.

**Comment by mcamurri** [comment]
I'm sorry, how can I "pause" the LCM thread?

When simulating with Gazebo, I can press the pause button, but on the real robot I just can't stop the LCM flow. Or you mean I can just press the pause button on the signal-scope itself?

Isn't there a way to automatically pause the thread from within the signal-scope when a new script is loaded?

**Comment by wxmerkt** [comment]
Is this what you are looking for? https://github.com/openhumanoids/signal-scope/commit/ad1a6bcd89c32c79b88a9b1ae1d8a2e810af991a (i.e. Pat merged a fix to this bug ~2 weeks ago and it is now part of the master tip of the repository)

**Comment by patmarion** [comment]
Right, this should be fixed.  If you have the latest version of signal-scope and still experience a crash, please let me know.

**Comment by mcamurri** [comment]
I confirm that even with the latest commit, it is crashing in two ways:
1. When I try to reload the same python file twice, I get the following error: `Fatal Python error: GC object already tracked
   Aborted`. This issue happens randomly if I  try to load different ones at different times but without a clear pattern
2. Sometimes I just get a SEGFAULT, but apparently there is no a fixed pattern to reproduce the error.

**Comment by patmarion** [comment]
So it crashes when you are viewing live LCM, then you use File --> Open Python Script to load a new configuration (while LCM traffic is flowing), then it crashes when you click Open?

If it's repeatable, then try to click Pause on the signal scope toolbar, then do the File --> Open Python Script.  Please let me know if that always works without crashing.  The latest commit is supposed to have fixed it so that you don't need to press the pause button, but perhaps it's still not quite resolved.

**Comment by mcamurri** [comment]
I do confirm the crash even with the pause button pressed. I'll soon try to have a minimal example, but it seems really random.

**Comment by patmarion** [comment]
Ok I'll try to repeat it on my computer.  I thought the problem was fixed but perhaps it is not completely fixed.  What operating system are you on?

**Comment by mcamurri** [comment]
Sorry for the late reply: Ubuntu 14.04

**Comment by patmarion** [comment]
Ok thanks, I can repeat the crash.
